/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start browser-bound Google sign-in
         * @description Uses fixed local destination and one-time state, nonce, and PKCE. It creates no Organization or Owner.
         */
        get: operations["startGoogleAuthentication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Complete browser-bound Google sign-in
         * @description Verifies the returned authorization response and initiating browser binding, maps the verified identity to a local person, and rotates the local session. Provider tokens and provider subject/email are not returned. Failure grants no session or Owner; redirects use a fixed local destination and never reflect arbitrary return URLs, referrers, codes, or provider errors.
         */
        get: operations["completeGoogleAuthentication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read current local session identity */
        get: operations["getCurrentPerson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the current local session
         * @description Requires same-origin request and CSRF token. Revokes the session and expires its cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization-establishments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare an Organization establishment
         * @description Creates a same-person, time-limited preparation only. This does not create an Organization or grant Owner authority. The returned frozen name and all four consequence fields must be disclosed before confirmation. Reads, mutations, and errors are private and no-store.
         */
        post: operations["prepareOrganizationEstablishment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization-establishments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PreparationId"];
            };
            cookie?: never;
        };
        /**
         * Read a same-person preparation or its established result
         * @description Only the initiating person's session may read it. Unknown and outside-person IDs have the same 404 shape. A committed result remains readable even when new establishments are unavailable or its preparation has expired.
         */
        get: operations["getOrganizationEstablishment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization-establishments/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PreparationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a disclosed preparation
         * @description Confirms only the frozen same-person preparation and consequence version. A committed result is replayed for the same person as historical result, not as a new grant subject to current hold or receipt expiry. An uncommitted stale or unknown consequence version requires a fresh preparation and disclosure. On transport loss or outcome_unknown, retain this preparation ID and read or replay this same command; do not blindly replace it. No caller-supplied identity, role, target, or override is accepted.
         */
        post: operations["confirmOrganizationEstablishment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Organizations where the current person is initial Owner
         * @description Uses a stable timestamp/UUID keyset and bounded page size. This authoritative private read remains available during a hold.
         */
        get: operations["listMyOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        /**
         * Read an Organization within current Owner scope
         * @description Enforces object-level Owner scope on the server. Unknown and outside-person IDs have the same 404 shape. The establishment effects are facts about establishment only and do not describe all current or future review outcomes.
         */
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            /** Format: uuid */
            person_id: string;
            csrf_token: string;
        };
        PrepareOrganizationRequest: {
            /** @description Trimmed to 1–200 Unicode scalar values; control characters are rejected and display is escaped. Duplicate names are allowed. */
            display_name: string;
        };
        Consequences: {
            /** @enum {boolean} */
            creates_organization_context: true;
            /** @enum {boolean} */
            assigns_you_initial_owner: true;
            /** @enum {string} */
            owner_authority_scope: "kencleng_internal";
            /** @enum {string} */
            organization_information_source: "organization_provided";
        };
        PreparationReceipt: {
            /** Format: uuid */
            id: string;
            display_name: string;
            /** Format: date-time */
            expires_at: string;
            /** @enum {string} */
            consequence_version: "c1-v1";
            consequences: components["schemas"]["Consequences"];
        };
        ConfirmOrganizationRequest: {
            consequence_version: string;
        };
        PreparationState: components["schemas"]["PreparedState"] | components["schemas"]["ExpiredState"] | components["schemas"]["EstablishedState"];
        PreparedState: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            state: "prepared";
            /** Format: uuid */
            id: string;
            display_name: string;
            /** Format: date-time */
            expires_at: string;
            /** @enum {string} */
            consequence_version: "c1-v1";
            consequences: components["schemas"]["Consequences"];
        };
        ExpiredState: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            state: "expired";
            /** Format: uuid */
            id: string;
        };
        EstablishedState: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            state: "established";
            organization: components["schemas"]["OrganizationView"];
        };
        OrganizationPage: {
            items: components["schemas"]["OrganizationView"][];
            next_cursor: string | null;
        };
        OrganizationView: {
            /** Format: uuid */
            id: string;
            display_name: string;
            /** Format: date-time */
            established_at: string;
            /** Format: uuid */
            established_by_person_id: string;
            /** Format: uuid */
            initial_owner_person_id: string;
            /** @enum {string} */
            your_role: "owner";
            /** @enum {string} */
            owner_authority_scope: "kencleng_internal";
            /** @enum {string} */
            information_source: "organization_provided";
            establishment_effects: {
                /** @enum {boolean} */
                organization_review_performed: false;
                /** @enum {boolean} */
                external_authority_verified: false;
                /** @enum {boolean} */
                campaign_curation_performed: false;
            };
        };
        ErrorEnvelope: {
            error: {
                /** @enum {string} */
                code: "invalid_request" | "invalid_organization_input" | "authentication_required" | "request_not_allowed" | "not_found" | "consequence_changed" | "preparation_expired" | "establishment_unavailable" | "processing_unavailable" | "outcome_unknown" | "too_many_requests";
                /** @description Safe localized message. It does not expose implementation details or unnecessary personal data. */
                message: string;
                request_id: string;
            };
        };
    };
    responses: {
        /** @description Invalid JSON/path/body or unknown authority-bearing field; no mutation */
        InvalidRequest: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Name requires correction; no success */
        InvalidOrganizationInput: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Valid local session required; client must not infer success */
        AuthenticationRequired: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Origin or CSRF denied before processing */
        RequestNotAllowed: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Unknown or outside-person object; identical response shape */
        NotFound: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Uncommitted consequence version is stale or unknown; prepare again and redisclose */
        ConsequenceChanged: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Uncommitted preparation expired; create a new preparation. Committed receipt remains readable. */
        PreparationExpired: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Bounded login or preparation abuse control */
        TooManyRequests: {
            headers: {
                "Cache-Control": components["headers"]["PrivateNoStore"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        CsrfToken: string;
        PreparationId: string;
        OrganizationId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Response is private and must not be stored */
        PrivateNoStore: "private, no-store";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startGoogleAuthentication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google authorization endpoint */
            302: {
                headers: {
                    Location?: string;
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    completeGoogleAuthentication: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fixed local application destination after callback processing */
            302: {
                headers: {
                    Location?: string;
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    /** @description Rotated opaque local session cookie after successful verification */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid callback; no session granted; fixed local error redirect */
            400: {
                headers: {
                    Location?: string;
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentPerson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local person and CSRF token; contains no provider identity */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked and cookie expired */
            204: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    /** @description Expired local session cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["RequestNotAllowed"];
        };
    };
    prepareOrganizationEstablishment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrepareOrganizationRequest"];
            };
        };
        responses: {
            /** @description Preparation receipt; no Organization or Owner exists yet */
            201: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreparationReceipt"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["RequestNotAllowed"];
            422: components["responses"]["InvalidOrganizationInput"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getOrganizationEstablishment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PreparationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prepared, expired, or established state */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreparationState"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            404: components["responses"]["NotFound"];
        };
    };
    confirmOrganizationEstablishment: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                id: components["parameters"]["PreparationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmOrganizationRequest"];
            };
        };
        responses: {
            /** @description Established Organization, including same-result replay */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstablishedState"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["RequestNotAllowed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["ConsequenceChanged"];
            410: components["responses"]["PreparationExpired"];
            /** @description `establishment_unavailable` means the guard is closed, missing, or unreadable and is not a dispute verdict for every candidate. `processing_unavailable` means a confirmed pre-commit database, lock, or service failure and permits a safe retry of this same command. `outcome_unknown` means commit acknowledgement or transport outcome is unknown; retain the preparation ID and read or replay this same command, without assuming rollback or blindly replacing it. */
            503: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listMyOrganizations: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scoped Organization page */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationPage"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authoritative private Organization view */
            200: {
                headers: {
                    "Cache-Control": components["headers"]["PrivateNoStore"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationView"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            404: components["responses"]["NotFound"];
        };
    };
}
